easy_admin:
    site_name: gogokick.com
    user:
        avatar_property_path: 'getAvatar'
    design:
        menu:
            - { entity: User, label: 'Users', icon: 'user' }
    entities:
        User:
            class: App\Entity\User
            list:
                fields:
                    - id
                    - isEnabled
                    - { property: 'email', label: 'Email', type: 'string' }
                    - { property: 'name', label: 'Name', type: 'string' }
                    - dateCreated
                    - dateLastLogin
            form:
                fields:
                    - email
                    - name
                    - avatar
                    - { property: 'bio', type_options: { required: false, empty_data: '' } }
                    - skills
                    - isEnabled
