sonata_admin:
    title: 'GoGoKick Admin'
    title_logo: https://gogokick.com/images/logo-2.png
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
