twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['_forms/bootstrap_4_layout.html.twig', '@FOSCKEditor/Form/ckeditor_widget.html.twig']
    globals:
        siteName: GoGoKick
        titleSuffix: - GoGoKick
