parameters:
    aws.region:  'us-east-1'
    aws.version: 'latest'
    aws.key:     '%env(AWS_KEY)%'
    aws.secret:  '%env(AWS_SECRET)%'

    cdn:
        screenshots:
            s3:
                folder:       'screenshots'
                bucket:       'assets.gogokick.com'
                cacheControl: 'max-age=300'
            cloudfront:
                id:  'E3E733268WBTQY'
                url: 'd24gkgs6s9hlg4.cloudfront.net'

        assets:
            s3:
                folder:       'assets'
                bucket:       'assets.gogokick.com'
                cacheControl: 'max-age=31536000'
            cloudfront:
                id:  'E3E733268WBTQY'
                url: 'd24gkgs6s9hlg4.cloudfront.net'

        project_images:
            s3:
                folder:       'project-images'
                bucket:       'assets.gogokick.com'
                cacheControl: 'max-age=31536000'
            cloudfront:
                id:  'E3E733268WBTQY'
                url: 'd24gkgs6s9hlg4.cloudfront.net'
            size:
                width: 1024
                height: 576

        block_images:
            s3:
                folder:       'block-images'
                bucket:       'assets.gogokick.com'
                cacheControl: 'max-age=31536000'
            cloudfront:
                id:  'E3E733268WBTQY'
                url: 'd24gkgs6s9hlg4.cloudfront.net'

        avatars:
            s3:
                folder:       'avatars'
                bucket:       'assets.gogokick.com'
                cacheControl: 'max-age=31536000'
            cloudfront:
                id:  'E3E733268WBTQY'
                url: 'd24gkgs6s9hlg4.cloudfront.net'
            size:
                width: 200
                height: 200

        downloads:
            s3:
                folder:       'downloads'
                bucket:       'assets.gogokick.com'
                cacheControl: 'max-age=300'
            cloudfront:
                id:  'E3E733268WBTQY'
                url: 'd24gkgs6s9hlg4.cloudfront.net'
