# Editor permissions
# @see assets/js/utils/acl.js
# @see https://github.com/GorillaStack/acl
parameters:
    permissions:
        roles:
            - name: owner
            - name: lead
            - name: writer
            - name: graphics
            - name: video
            - name: audio
        resources:
            - name: project
            - name: blocks
            - name: block-text
            - name: block-image
            - name: block-video
            - name: block-audio
            - name: teamMember
        rules:
            - role: owner
              access: allow
              privileges: ~
              resources: ~
            - role: lead
              access: allow
              privileges:
                  - view
                  - edit
                  - add
                  - delete
                  - drag
                  - lock
                  - settings
              resources:
                  - blocks
                  - block-text
                  - block-image
                  - block-video
                  - block-audio
            - role: lead
              access: allow
              privileges:
                  - view
              resources:
                  - teamMember
            - role: writer
              access: allow
              privileges:
                  - view
              resources:
                  - teamMember
            - role: writer
              access: allow
              privileges:
                  - edit
              resources:
                  - block-text
            - role: graphics
              access: allow
              privileges:
                  - view
              resources:
                  - teamMember
            - role: graphics
              access: allow
              privileges:
                  - edit
              resources:
                  - block-image
            - role: video
              access: allow
              privileges:
                  - view
              resources:
                  - teamMember
            - role: video
              access: allow
              privileges:
                  - edit
              resources:
                  - block-video
            - role: audio
              access: allow
              privileges:
                  - view
              resources:
                  - teamMember
            - role: audio
              access: allow
              privileges:
                  - edit
              resources:
                  - block-audio
