# Editor permissions
# @see assets/js/utils/acl.js
# @see https://github.com/GorillaStack/acl
parameters:
    permissions:
        roles:
            - name: owner
            - name: lead
            - name: writer
            - name: graphics
            - name: video
            - name: audio
            - name: guest

        resources:
            - name: notes
            - name: project
            - name: blocks
            - name: block-text
            - name: block-image
            - name: block-video
            - name: block-audio
            - name: teamMember

        rules:
            - role: owner
              access: allow
              privileges: ~
              resources: ~

            - role: lead
              access: allow
              privileges:
                  - view
                  - edit
                  - add
                  - delete
                  - drag
                  - lock
                  - notes
                  - settings
              resources:
                  - blocks
                  - block-text
                  - block-image
                  - block-video
                  - block-audio

            - role: lead
              access: allow
              privileges:
                  - view
              resources:
                  - teamMember

            - role: lead
              access: allow
              privileges:
                  - delete
              resources:
                  - notes

            - role: lead
              access: allow
              privileges:
                  - settings
                  - preview
                  - export
                  - undo
              resources:
                  - project

            - role: writer
              access: allow
              privileges:
                  - view
              resources:
                  - teamMember

            - role: writer
              access: allow
              privileges:
                  - edit
                  - notes
              resources:
                  - block-text

            - role: writer
              access: allow
              privileges:
                  - undo
              resources:
                  - project

            - role: graphics
              access: allow
              privileges:
                  - view
              resources:
                  - teamMember

            - role: graphics
              access: allow
              privileges:
                  - edit
                  - notes
              resources:
                  - block-image

            - role: graphics
              access: allow
              privileges:
                  - undo
              resources:
                  - project

            - role: video
              access: allow
              privileges:
                  - view
              resources:
                  - teamMember

            - role: video
              access: allow
              privileges:
                  - edit
                  - notes
              resources:
                  - block-video

            - role: video
              access: allow
              privileges:
                  - undo
              resources:
                  - project

            - role: audio
              access: allow
              privileges:
                  - view
              resources:
                  - teamMember

            - role: audio
              access: allow
              privileges:
                  - edit
                  - notes
              resources:
                  - block-audio

            - role: audio
              access: allow
              privileges:
                  - undo
              resources:
                  - project
