#index:
#    path: /
#    controller: App\Controller\DefaultController::index
editor:
    path: "/editor/{catchAll}"
    defaults: { _controller: 'App\Controller\HomeController::editorAction' }
    requirements:
        catchAll: ".*"


