#index:
#    path: /
#    controller: App\Controller\DefaultController::index
editor_blank:
    path: "/editor"
    defaults: { _controller: 'App\Controller\HomeController::editorAction' }
editor:
    path: "/editor/{catchAll}"
    defaults: { _controller: 'App\Controller\HomeController::editorAction' }
    requirements:
        catchAll: ".*"


