#index:
#    path: /
#    controller: App\Controller\DefaultController::index
easy_admin_bundle:
    resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
    prefix: /admin
    type: annotation
editor_blank:
    path: "/editor"
    defaults: { _controller: 'App\Controller\HomeController::editorAction' }
editor_project:
    path: "/editor/{id}"
    defaults: { _controller: 'App\Controller\HomeController::editorAction' }
    requirements:
        id: '\d+'
dashboard_blank:
    path: "/dashboard"
    defaults: { _controller: 'App\Controller\HomeController::editorAction' }
home:
    path: "/{catchAll}"
    defaults: { _controller: 'App\Controller\HomeController::editorAction' }
    requirements:
        catchAll: ".*"
